import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// What build am I actually running?
//
// T13, filed after T12 cost a diagnosis cycle. The installed app reported
// version 0.0.0 and carried nothing identifying its commit or build date, so a
// stale packaged build was indistinguishable from a current one — settling it
// meant reading operations.js out of the shipped bundle and diffing against
// commit timestamps.
//
// build-info.json is generated by scripts/write-build-info.js at package time
// and is deliberately NOT committed: it would churn on every build and its
// value is only ever "what did THIS artifact come from".
//
// A development run has no such file, and that is a meaningful answer rather
// than a missing one — an unpackaged build is identified by its DEV badge
// (ADR 2026-07-28), not by a commit.

const DEV_BUILD = { commit: null, builtAt: null, isDev: true }

export function parseBuildInfo(raw) {
  if (typeof raw !== 'string' || raw.length === 0) return DEV_BUILD
  let parsed
  try {
    parsed = JSON.parse(raw)
  } catch {
    // A corrupt stamp must not take the app down, and must never be reported as
    // a real build — an unknown provenance is exactly what this exists to flag.
    return DEV_BUILD
  }
  if (!parsed || typeof parsed !== 'object') return DEV_BUILD
  const commit = typeof parsed.commit === 'string' && parsed.commit.length > 0 ? parsed.commit : null
  const builtAt = typeof parsed.builtAt === 'string' && parsed.builtAt.length > 0 ? parsed.builtAt : null
  if (!commit && !builtAt) return DEV_BUILD
  return { commit, builtAt, isDev: false }
}

// Short, human-scannable label for the UI. Kept here rather than in the
// component so the "what build is this" answer has one definition.
export function formatBuildLabel(info, version) {
  const v = typeof version === 'string' && version.length > 0 ? `v${version}` : null
  if (!info || info.isDev) return v ? `${v} · dev` : 'dev'
  const parts = []
  if (v) parts.push(v)
  if (info.commit) parts.push(info.commit.slice(0, 7))
  if (info.builtAt) parts.push(info.builtAt.slice(0, 10))
  return parts.join(' · ')
}

export function readBuildInfo(dir) {
  const base = dir ?? path.dirname(fileURLToPath(import.meta.url))
  try {
    return parseBuildInfo(fs.readFileSync(path.join(base, 'build-info.json'), 'utf8'))
  } catch {
    return DEV_BUILD
  }
}
