import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// What build am I actually running?
//
// T13, filed after T12 cost a diagnosis cycle. The installed app reported
// version 0.0.0 and carried nothing identifying its commit or build date, so a
// stale packaged build was indistinguishable from a current one — settling it
// meant reading operations.js out of the shipped bundle and diffing against
// commit timestamps.
//
// build-info.json is generated by scripts/write-build-info.js at package time
// and is deliberately NOT committed: it would churn on every build and its
// value is only ever "what did THIS artifact come from".
//
// A development run must report itself as a development run, and that is a
// meaningful answer rather than a missing one — an unpackaged build is
// identified by its DEV badge (ADR 2026-07-28), not by a commit.
//
// T14: this used to rely on the file's ABSENCE to detect a dev run, with the
// stated assumption that "a development run has no such file". That assumption
// is false on any machine that has ever packaged: write-build-info.js leaves
// build-info.json in the working tree, it is gitignored rather than cleaned up,
// and every later dev run then read it and claimed to be a packaged build from
// whatever commit was last shipped. A stale, plausible-looking commit is exactly
// the confusion T13 was filed to eliminate, so the packaged state is now stated
// explicitly by the caller instead of inferred from the filesystem.

const DEV_BUILD = { commit: null, builtAt: null, isDev: true }

export function parseBuildInfo(raw) {
  if (typeof raw !== 'string' || raw.length === 0) return DEV_BUILD
  let parsed
  try {
    parsed = JSON.parse(raw)
  } catch {
    // A corrupt stamp must not take the app down, and must never be reported as
    // a real build — an unknown provenance is exactly what this exists to flag.
    return DEV_BUILD
  }
  if (!parsed || typeof parsed !== 'object') return DEV_BUILD
  const commit = typeof parsed.commit === 'string' && parsed.commit.length > 0 ? parsed.commit : null
  const builtAt = typeof parsed.builtAt === 'string' && parsed.builtAt.length > 0 ? parsed.builtAt : null
  if (!commit && !builtAt) return DEV_BUILD
  return { commit, builtAt, isDev: false }
}

// Short, human-scannable label for the UI. Kept here rather than in the
// component so the "what build is this" answer has one definition.
export function formatBuildLabel(info, version) {
  const v = typeof version === 'string' && version.length > 0 ? `v${version}` : null
  if (!info || info.isDev) return v ? `${v} · dev` : 'dev'
  const parts = []
  if (v) parts.push(v)
  if (info.commit) parts.push(info.commit.slice(0, 7))
  if (info.builtAt) parts.push(info.builtAt.slice(0, 10))
  return parts.join(' · ')
}

// `isPackaged` is required in spirit and defaulted to true only so the existing
// signature keeps working; callers inside the app MUST pass app.isPackaged.
// An unpackaged run never reads the stamp at all — not "reads it and ignores
// it", but never reads it — so a stale file on disk cannot influence the answer.
export function readBuildInfo(dir, isPackaged = true) {
  if (!isPackaged) return DEV_BUILD
  const base = dir ?? path.dirname(fileURLToPath(import.meta.url))
  try {
    return parseBuildInfo(fs.readFileSync(path.join(base, 'build-info.json'), 'utf8'))
  } catch {
    return DEV_BUILD
  }
}

// The app's own version, read from package.json rather than app.getVersion().
//
// T14, second cause: app.getVersion() returns ELECTRON's version (e.g. 43.1.1)
// in an unpackaged run, because there is no packaged Info.plist to read. Only a
// packaged build returns the app's real 0.1.0, so the footer read
// "v43.1.1 · …" in development — a version number belonging to a different
// piece of software entirely.
export function readAppVersion(dir) {
  const base = dir ?? path.dirname(fileURLToPath(import.meta.url))
  try {
    const raw = fs.readFileSync(path.join(base, '..', 'package.json'), 'utf8')
    const v = JSON.parse(raw).version
    return typeof v === 'string' && v.length > 0 ? v : null
  } catch {
    return null
  }
}
