// @vitest-environment node
//
// T332 (docs/work/specs/2026-10-03-t332-client-admin-minting-design.md) — closing the
// approveDevice/revokeDevice mode==='client' gap the T331 ADR's "Blast radius" section already
// named: the camp_authority_log mint is mode-agnostic by construction, but the app-level
// mode==='client' throw in electron/main.js still blocked a Client device from ever reaching it.
//
// RED-before-green: this file is written and run BEFORE the two guards are relaxed, so the first
// two tests below must fail against the mode==='client' throw. Multiple "device identities" share
// one db/document, exactly as electron/main.authorityEndToEnd.test.js's own quorum test does
// ("every evaluation below reads dbF's OWN authority_cache" standing in for a real merge) — this
// is the precedented, cheaper alternative to standing up real libp2p nodes per test.
import { describe, it, expect, beforeEach, afterEach, afterAll, vi } from 'vitest'
import os from 'node:os'
import { randomUUID } from 'node:crypto'

vi.mock('electron', () => ({
  app: { getPath: vi.fn(() => os.tmpdir()), whenReady: vi.fn(() => Promise.resolve()), on: vi.fn() },
  BrowserWindow: vi.fn(),
  ipcMain: { handle: vi.fn() },
  contextBridge: { exposeInMainWorld: vi.fn() },
  ipcRenderer: { invoke: vi.fn(), on: vi.fn() },
}))

import fs from 'node:fs'
import path from 'node:path'
import { openTemplatedDb, cleanupTemplatedDbs } from './db/testDbTemplate.js'
import { getOrCreateDeviceId } from './db/localDb.js'
import { createUser, ensureHostSigningKey } from './auth/localAuth.js'
import { makeHandlers } from './main.js'
import { mintGenesisEntry, mintGrantEntry, mintRevokeEntry } from './automerge/authorityLog.js'
import { projectEntity } from './automerge/projector.js'
import { getCurrentDoc, setUserDataDirGetter, resetForTests as resetLiveDocForTests } from './sync/automerge/liveDoc.js'
import { ensureDeviceIdentity } from './auth/deviceIdentity.js'

let db, founderDeviceId, userDataDir, sharedPeerId

function localTestWrite(byDeviceId) {
  return async (args) => {
    const { appendOp } = await import('./ops/operations.js')
    return { status: 'applied', op: appendOp(db, { ...args, author_user_id: null, device_id: byDeviceId, parent_op_id: null }) }
  }
}

function insertDevice(id, { authorized = true } = {}) {
  db.prepare(
    "INSERT OR IGNORE INTO devices (id, name, pairing_status, authorized_at) VALUES (?, ?, ?, ?)"
  ).run(id, id, authorized ? 'authorized' : 'pending', authorized ? new Date().toISOString() : null)
}

function authorityCacheStatus(deviceId) {
  return db.prepare('SELECT status FROM authority_cache WHERE device_id = ?').get(deviceId)?.status ?? null
}

function projectAuthority() {
  projectEntity(db, getCurrentDoc(db), 'camp_authority_log')
}

/** Seeds a camp, makes `founderDeviceId` the Host-signing-key holder and founder (genesis entry). */
async function seedFounderCamp() {
  const campId = randomUUID()
  db.prepare('INSERT INTO camps (id, name, signing_secret) VALUES (?, ?, ?)').run(campId, 'T332 Camp', 'a'.repeat(64))
  const hostKey = ensureHostSigningKey(db)
  db.prepare('UPDATE camps SET signing_public_key = ? WHERE id = ?').run(hostKey.public_key, campId)
  insertDevice(founderDeviceId)
  const founder = await createUser(db, { camp_id: campId, name: 'Founder', pin: '135790', role: 'admin' }, localTestWrite(founderDeviceId))
  db.prepare("UPDATE devices SET authorized_by_user_id = ? WHERE id = ?").run(founder.id, founderDeviceId)
  const { peerId: founderPeerId } = await ensureDeviceIdentity(db)
  sharedPeerId = founderPeerId
  mintGenesisEntry(db, { founderDeviceId, founderPeerId })
  projectAuthority()
  return { campId, founder }
}

// All "device identities" in this file's tests sign through the ONE shared `db`, which holds a
// SINGLE device_identity_key (the founder's). Every target_peer_id below is therefore
// deliberately the SAME peer id — the signature a later admin's REAL handler call produces is
// genuinely generated by that one underlying key, and giving every grantee the matching peer id
// to verify against is what lets authorityReplay's real signature check pass, exactly as it would
// if each device held its own distinct key (which electron/main.authorityEndToEnd.test.js's own
// quorum test exercises, with separate per-device key-only dbs). The authorization/guard
// composition this ticket is actually about does not depend on which identity shape is used.
/** Creates a user + device and mints a grant entry making it an admin, via the founder. */
async function grantAdmin({ campId, name, pin, deviceId }) {
  insertDevice(deviceId)
  const user = await createUser(db, { camp_id: campId, name, pin, role: 'admin' }, localTestWrite(founderDeviceId))
  mintGrantEntry(db, { targetDeviceId: deviceId, targetPeerId: sharedPeerId, signerDeviceId: founderDeviceId })
  projectAuthority()
  return user
}

beforeEach(() => {
  userDataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'shoresh-t332-'))
  setUserDataDirGetter(() => userDataDir)
  const templated = openTemplatedDb()
  db = templated.db
  founderDeviceId = getOrCreateDeviceId(db)
})

afterEach(() => {
  resetLiveDocForTests()
  try { db.close() } catch { /* already closed */ }
  fs.rmSync(userDataDir, { recursive: true, force: true })
})

afterAll(() => {
  cleanupTemplatedDbs()
})

describe('T332 — client-mode admin minting', () => {
  it('a client-mode admin mints a founder-removal revoke end-to-end', async () => {
    const { campId } = await seedFounderCamp()
    const admin2DeviceId = 'device-admin2'
    const admin2 = await grantAdmin({ campId, name: 'Admin2', pin: '246813', deviceId: admin2DeviceId })
    expect(authorityCacheStatus(admin2DeviceId)).toBe('admin')

    const handlers2 = makeHandlers(db, admin2DeviceId, { getAutomergeSyncNode: () => null })
    await handlers2.chooseMode({ mode: 'client' })
    const { token: admin2Token } = await handlers2.login({ name: 'Admin2', pin: '246813' })
    expect(admin2Token).toEqual(expect.any(String))

    // (a) must not throw the mode==='client' error — it must not exist after this change.
    const result = handlers2.revokeDevice({ token: admin2Token, deviceId: founderDeviceId, reason: 'client-admin-mint' })
    expect(result.revoked).toBe(true)

    // (b) a signed revoke entry lands in camp_authority_log with signer_device_id = admin-2.
    const logged = db.prepare(
      "SELECT kind, signer_device_id FROM applied_authority_log WHERE target_device_id = ? AND kind = 'revoke'"
    ).get(founderDeviceId)
    expect(logged).toEqual({ kind: 'revoke', signer_device_id: admin2DeviceId })

    // (c)/(d) after replay, the founder is refused — even though the founder's device is the
    // ONLY one that ever held host_signing_key, confirming no Host-only path was required.
    expect(authorityCacheStatus(founderDeviceId)).toBe('revoked')
    void admin2
  })

  it('a client-mode staff caller is refused minting, before mintRevokeEntry is ever called', async () => {
    const { campId } = await seedFounderCamp()
    const staffDeviceId = 'device-staff'
    insertDevice(staffDeviceId)
    await createUser(db, { camp_id: campId, name: 'StaffPerson', pin: '111111', role: 'staff' }, localTestWrite(founderDeviceId))

    const handlersStaff = makeHandlers(db, staffDeviceId, { getAutomergeSyncNode: () => null })
    await handlersStaff.chooseMode({ mode: 'client' })
    const { token: staffToken } = await handlersStaff.login({ name: 'StaffPerson', pin: '111111' })

    const countBefore = db.prepare("SELECT COUNT(*) c FROM applied_authority_log").get().c

    expect(() => handlersStaff.revokeDevice({ token: staffToken, deviceId: founderDeviceId }))
      .toThrow()

    const countAfter = db.prepare("SELECT COUNT(*) c FROM applied_authority_log").get().c
    expect(countAfter).toBe(countBefore)
  })

  it('composes with T331 quorum: one client-admin vote against another admin does not remove it alone', async () => {
    const { campId } = await seedFounderCamp()
    const admin2DeviceId = 'device-admin2-q'
    const admin3DeviceId = 'device-admin3-q'
    await grantAdmin({ campId, name: 'Admin2Q', pin: '246813', deviceId: admin2DeviceId })
    await grantAdmin({ campId, name: 'Admin3Q', pin: '357914', deviceId: admin3DeviceId })
    // N=3 admins total (founder, admin2, admin3); threshold over the 2 OTHER admins is
    // floor((3-1)/2)+1 = 2 — one client-mode vote against admin3 must not remove it alone.
    expect(authorityCacheStatus(admin3DeviceId)).toBe('admin')

    const handlers2 = makeHandlers(db, admin2DeviceId, { getAutomergeSyncNode: () => null })
    await handlers2.chooseMode({ mode: 'client' })
    const { token: admin2Token } = await handlers2.login({ name: 'Admin2Q', pin: '246813' })

    const result = handlers2.revokeDevice({ token: admin2Token, deviceId: admin3DeviceId, reason: 'vote 1 of 2' })
    // T332 fold-in (Red Hat HIGH, Art. V) — gated on the real quorum state, not optimistic.
    expect(result.revoked).toBe(false)
    expect(authorityCacheStatus(admin3DeviceId)).toBe('admin') // quorum is not met yet.

    // Second vote, from the founder (standing in for the second other admin's own vote landing
    // via merge) — now quorum is met and the target is actually removed.
    mintRevokeEntry(db, { targetDeviceId: admin3DeviceId, signerDeviceId: founderDeviceId })
    projectAuthority()
    expect(authorityCacheStatus(admin3DeviceId)).toBe('revoked')
  })

  it('a client-mode admin approves a new device and grants admin end-to-end', async () => {
    const { campId } = await seedFounderCamp()
    const admin2DeviceId = 'device-admin2-approve'
    await grantAdmin({ campId, name: 'Admin2Approve', pin: '246813', deviceId: admin2DeviceId })

    const newDeviceId = 'device-new-join'
    insertDevice(newDeviceId, { authorized: false })

    const handlers2 = makeHandlers(db, admin2DeviceId, { getAutomergeSyncNode: () => ({ sendPairingApproved: async () => true }) })
    await handlers2.chooseMode({ mode: 'client' })
    const { token: admin2Token } = await handlers2.login({ name: 'Admin2Approve', pin: '246813' })

    // (a) no throw.
    const result = await handlers2.approveDevice({ token: admin2Token, deviceId: newDeviceId, makeAdmin: true })
    expect(result).toEqual({ deviceId: newDeviceId, authorized: true })

    // (b) the local devices row is authorized.
    const row = db.prepare('SELECT authorized_at, pairing_status FROM devices WHERE id = ?').get(newDeviceId)
    expect(row.authorized_at).toEqual(expect.any(String))
    expect(row.pairing_status).toBe('authorized')

    // (c) a signed grant entry lands in camp_authority_log.
    const logged = db.prepare(
      "SELECT kind, signer_device_id FROM applied_authority_log WHERE target_device_id = ? AND kind = 'grant'"
    ).get(newDeviceId)
    expect(logged).toEqual({ kind: 'grant', signer_device_id: admin2DeviceId })

    // (d) after projection, the new device is recognized as a valid admin — standing in for a
    // third peer that never ran approveDevice itself (same document, as in the T331 quorum test).
    expect(authorityCacheStatus(newDeviceId)).toBe('admin')
  })

  it('never touches host_signing_key or camps.signing_public_key from the client path', async () => {
    const { campId } = await seedFounderCamp()
    const admin2DeviceId = 'device-admin2-hk'
    await grantAdmin({ campId, name: 'Admin2HK', pin: '246813', deviceId: admin2DeviceId })
    const newDeviceId = 'device-new-hk'
    insertDevice(newDeviceId, { authorized: false })

    const hostKeyBefore = db.prepare('SELECT * FROM host_signing_key').get()
    const signingPubBefore = db.prepare('SELECT signing_public_key FROM camps LIMIT 1').get().signing_public_key

    const handlers2 = makeHandlers(db, admin2DeviceId, { getAutomergeSyncNode: () => ({ sendPairingApproved: async () => true }) })
    await handlers2.chooseMode({ mode: 'client' })
    const { token: admin2Token } = await handlers2.login({ name: 'Admin2HK', pin: '246813' })

    await handlers2.approveDevice({ token: admin2Token, deviceId: newDeviceId, makeAdmin: true })
    handlers2.revokeDevice({ token: admin2Token, deviceId: founderDeviceId })

    expect(db.prepare('SELECT * FROM host_signing_key').get()).toEqual(hostKeyBefore)
    expect(db.prepare('SELECT signing_public_key FROM camps LIMIT 1').get().signing_public_key).toBe(signingPubBefore)
  })

  it('denyDevice is unchanged — still refuses in client mode (regression guard)', async () => {
    const { campId } = await seedFounderCamp()
    const admin2DeviceId = 'device-admin2-deny'
    await grantAdmin({ campId, name: 'Admin2Deny', pin: '246813', deviceId: admin2DeviceId })
    const pendingDeviceId = 'device-pending-deny'
    insertDevice(pendingDeviceId, { authorized: false })

    const handlers2 = makeHandlers(db, admin2DeviceId, { getAutomergeSyncNode: () => null })
    await handlers2.chooseMode({ mode: 'client' })
    const { token: admin2Token } = await handlers2.login({ name: 'Admin2Deny', pin: '246813' })

    expect(() => handlers2.denyDevice({ token: admin2Token, deviceId: pendingDeviceId }))
      .toThrow('Device management can only be done on the main computer.')
  })
})
