const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('shoresh', {
  chooseMode: (args) => ipcRenderer.invoke('shoresh:choose-mode', args),
  discoverHosts: () => ipcRenderer.invoke('shoresh:discover-hosts'),
  login: (args) => ipcRenderer.invoke('shoresh:login', args),
  createUser: (args) => ipcRenderer.invoke('shoresh:create-user', args),
  bootstrapCamp: (args) => ipcRenderer.invoke('shoresh:bootstrap-camp', args),
  write: (args) => ipcRenderer.invoke('shoresh:write', args),
  bulkReplace: (args) => ipcRenderer.invoke('shoresh:bulk-replace', args),
  verifySession: (args) => ipcRenderer.invoke('shoresh:verify-session', args),
  onOpApplied: (callback) => ipcRenderer.on('shoresh:op-applied', (_event, op) => callback(op)),
  onOpConflict: (callback) => ipcRenderer.on('shoresh:op-conflict', (_event, msg) => callback(msg)),
  getCamp: () => ipcRenderer.invoke('shoresh:get-camp'),
  listUsers: (token) => ipcRenderer.invoke('shoresh:list-users', { token }),
  list: (token, entity) => ipcRenderer.invoke('shoresh:list', { token, entity }),
  getDeviceId: (token) => ipcRenderer.invoke('shoresh:get-device-id', { token }),
  resolveConflict: (args) => ipcRenderer.invoke('shoresh:resolve-conflict', args),
  listPendingConflicts: (token) => ipcRenderer.invoke('shoresh:list-conflicts', { token }),
  getDevicePairingStatus: () => ipcRenderer.invoke('shoresh:get-device-pairing-status'),
  listPendingPairingRequests: (token) => ipcRenderer.invoke('shoresh:list-pending-pairing-requests', { token }),
  approveDevice: (args) => ipcRenderer.invoke('shoresh:approve-device', args),
  denyDevice: (args) => ipcRenderer.invoke('shoresh:deny-device', args),
  listDevices: (token) => ipcRenderer.invoke('shoresh:list-devices', { token }),
  revokeDevice: (args) => ipcRenderer.invoke('shoresh:revoke-device', args),
  onPairingRequest: (callback) => ipcRenderer.on('shoresh:pairing-request', (_event, data) => callback(data)),
  onPairingApproved: (callback) => ipcRenderer.on('shoresh:pairing-approved', () => callback()),
  onPairingDenied: (callback) => ipcRenderer.on('shoresh:pairing-denied', () => callback()),
  onTokenRenewed: (callback) => ipcRenderer.on('shoresh:token-renewed', (_event, data) => callback(data.token)),
  // §9 project-file lifecycle
  getCurrentProject: () => ipcRenderer.invoke('shoresh:get-current-project'),
  createProject: () => ipcRenderer.invoke('shoresh:create-project'),
  openProject: () => ipcRenderer.invoke('shoresh:open-project'),
  exportProject: () => ipcRenderer.invoke('shoresh:export-project'),
  backupProject: () => ipcRenderer.invoke('shoresh:backup-project'),
  restoreProject: () => ipcRenderer.invoke('shoresh:restore-project'),
  listRecentProjects: () => ipcRenderer.invoke('shoresh:list-recent-projects'),
  openRecentProject: (targetPath) => ipcRenderer.invoke('shoresh:open-recent-project', { path: targetPath }),
})
