// Shared inline style constants — import as: import { S } from '../styles/shared'
export const S = {
  btnPrimary: {
    padding: '7px 14px',
    background: 'var(--primary)',
    color: '#fff',
    border: 'none',
    borderRadius: 7,
    fontWeight: 700,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnSecondary: {
    padding: '7px 14px',
    background: 'var(--surface)',
    color: 'var(--text)',
    border: '1px solid var(--border)',
    borderRadius: 7,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  btnDanger: {
    padding: '7px 14px',
    background: 'none',
    color: 'var(--warning)',
    border: '1px solid var(--warning)',
    borderRadius: 7,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  th: {
    padding: '10px 14px',
    textAlign: 'left',
    fontSize: 12,
    fontFamily: 'var(--font-condensed)',
    fontWeight: 500,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  td: {
    padding: '10px 14px',
    textAlign: 'left',
    fontSize: 13,
  },
  input: {
    padding: '8px 10px',
    border: '1.5px solid var(--border)',
    borderRadius: 7,
    fontSize: 13,
    outline: 'none',
    background: 'var(--surface)',
    width: '100%',
    fontFamily: 'inherit',
  },
  label: {
    fontSize: 12,
    fontWeight: 500,
    color: 'var(--text-secondary)',
    display: 'block',
    marginBottom: 4,
  },
  modalSm: {
    background: 'var(--surface-elevated)',
    borderRadius: 12,
    padding: 28,
    maxWidth: 400,
    width: '100%',
  },
  modalLg: {
    background: 'var(--surface-elevated)',
    borderRadius: 12,
    padding: 28,
    width: 480,
    maxWidth: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  errorBanner: {
    background: '#fff5f5',
    border: '1px solid #f5c6c6',
    borderRadius: 6,
    padding: '10px 14px',
    marginBottom: 16,
    fontSize: 13,
    color: 'var(--warning)',
  },

  // --- Auth / onboarding shared primitives ---
  authPage: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100vh',
    background: 'var(--bg)',
    padding: 24,
    boxSizing: 'border-box',
  },
  authCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 10,
    padding: '40px 44px',
    maxWidth: 460,
    width: '100%',
    boxShadow: '0 2px 24px rgba(20,30,40,0.06)',
    boxSizing: 'border-box',
  },
  authLogoBlock: {
    marginBottom: 28,
    textAlign: 'left',
  },
  authLogo: {
    fontFamily: 'var(--font-condensed)',
    fontWeight: 700,
    fontSize: 28,
    color: 'var(--primary)',
    letterSpacing: '-0.5px',
  },
  authLogoSub: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-secondary)',
    marginTop: 2,
  },
  authEyebrow: {
    fontFamily: 'var(--font-condensed)',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: 'var(--text-secondary)',
    marginBottom: 6,
  },
  authTitle: {
    fontFamily: 'var(--font-condensed)',
    fontWeight: 700,
    fontSize: 22,
    color: 'var(--text)',
    letterSpacing: '-0.3px',
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 13,
    color: 'var(--text-secondary)',
    lineHeight: 1.6,
    marginBottom: 26,
  },
  authField: {
    width: '100%',
    padding: '10px 12px',
    border: '1.5px solid var(--border)',
    borderRadius: 7,
    fontSize: 14,
    fontFamily: 'inherit',
    outline: 'none',
    background: 'var(--bg)',
    color: 'var(--text)',
    boxSizing: 'border-box',
  },
  authLabel: {
    fontSize: 12,
    fontWeight: 500,
    display: 'block',
    marginBottom: 5,
    marginTop: 16,
    color: 'var(--text-secondary)',
  },
  authHint: {
    fontSize: 11,
    color: 'var(--text-secondary)',
    marginTop: 5,
  },
  authBtnPrimary: {
    display: 'block',
    width: '100%',
    padding: '11px 0',
    background: 'var(--primary)',
    color: '#fff',
    border: 'none',
    borderRadius: 7,
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: 22,
  },
  authLinkBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    fontSize: 12,
    cursor: 'pointer',
    padding: 0,
    fontFamily: 'inherit',
    textDecoration: 'underline',
  },
  authBackRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 18,
  },
  authBackBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--text-secondary)',
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: '4px 6px',
    marginLeft: -6,
    borderRadius: 5,
  },
  authErrorBox: {
    background: '#fff5f5',
    border: '1px solid #f5c6c6',
    borderRadius: 7,
    padding: '10px 12px',
    fontSize: 12,
    color: 'var(--warning)',
    marginBottom: 14,
    display: 'flex',
    gap: 8,
    alignItems: 'flex-start',
  },
  authChoiceCard: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    padding: '18px 18px',
    background: 'var(--surface)',
    border: '1.5px solid var(--border)',
    borderRadius: 10,
    textAlign: 'left',
    cursor: 'pointer',
    width: '100%',
    marginBottom: 12,
    transition: 'box-shadow 0.15s, border-color 0.15s',
    fontFamily: 'inherit',
  },
  authChoiceIcon: {
    width: 38,
    height: 38,
    borderRadius: 9,
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0,173,187,0.1)',
    color: 'var(--primary)',
    fontSize: 18,
  },
  authChoiceTitle: {
    fontFamily: 'var(--font-condensed)',
    fontWeight: 700,
    fontSize: 15,
    color: 'var(--text)',
    marginBottom: 3,
  },
  authChoiceDesc: {
    fontSize: 12,
    color: 'var(--text-secondary)',
    lineHeight: 1.5,
  },
  authChoiceChevron: {
    marginLeft: 'auto',
    alignSelf: 'center',
    color: 'var(--text-secondary)',
    fontSize: 15,
    paddingLeft: 8,
  },
  authHostItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '13px 14px',
    border: '1.5px solid var(--border)',
    borderRadius: 8,
    marginBottom: 8,
    cursor: 'pointer',
    transition: 'border-color 0.15s, background 0.15s',
    background: 'var(--surface)',
    width: '100%',
    textAlign: 'left',
    fontFamily: 'inherit',
  },
  authHostDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--success)',
    flexShrink: 0,
    boxShadow: '0 0 0 3px rgba(0,170,89,0.15)',
  },
  authHostName: {
    fontWeight: 600,
    fontSize: 13.5,
    color: 'var(--text)',
  },
  authHostMeta: {
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-secondary)',
    marginTop: 1,
  },
  authRolePill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 5,
    fontFamily: 'var(--font-mono)',
    fontSize: 10,
    fontWeight: 600,
    color: 'var(--text-secondary)',
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 99,
    padding: '3px 9px',
    marginBottom: 18,
  },
  authLockoutBox: {
    textAlign: 'center',
    padding: '18px 14px',
    background: '#fffaf0',
    border: '1px solid #f5deb0',
    borderRadius: 8,
    marginTop: 16,
  },
  authLockoutTitle: {
    fontFamily: 'var(--font-condensed)',
    fontWeight: 700,
    fontSize: 14,
    color: '#8a6110',
    marginBottom: 4,
  },
  authLockoutDesc: {
    fontSize: 12,
    color: '#8a6110',
    lineHeight: 1.5,
  },
  authLockoutTimer: {
    fontFamily: 'var(--font-mono)',
    fontWeight: 700,
    fontSize: 15,
    color: '#8a6110',
    marginTop: 8,
  },

  // --- Merge / conflict resolution (ConflictsScreen) ---
  mergeCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    padding: '18px 20px',
    marginBottom: 14,
    overflow: 'hidden',
    transition: 'max-height 0.35s ease, opacity 0.35s ease, margin 0.35s ease, padding 0.35s ease, border-color 0.35s ease',
  },
  mergeChoiceBox: {
    flex: 1,
    minWidth: 220,
    background: 'var(--bg)',
    border: '1.5px solid var(--border)',
    borderRadius: 9,
    padding: 14,
    transition: 'border-color 0.15s',
  },
  mergeChoiceBoxHover: {
    borderColor: 'var(--primary)',
  },
  mergeMeta: {
    fontSize: 11.5,
    fontFamily: 'var(--font-mono)',
    color: 'var(--text-secondary)',
  },
  mergeBtnKeep: {
    padding: '7px 14px',
    background: 'var(--surface)',
    color: 'var(--text)',
    border: '1px solid var(--border)',
    borderRadius: 7,
    fontWeight: 600,
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
    width: '100%',
    marginTop: 12,
    transition: 'background 0.12s, color 0.12s',
  },
  mergePinLock: {
    textAlign: 'center',
    padding: '10px 0',
    color: 'var(--text-secondary)',
    fontSize: 13,
  },
  mergeEmptyState: {
    textAlign: 'center',
    padding: '60px 16px',
  },
  mergeConfirmed: {
    textAlign: 'center',
    padding: '20px 0',
    color: 'var(--success)',
    fontFamily: 'var(--font-condensed)',
    fontWeight: 700,
    fontSize: 15,
    transition: 'opacity 0.15s',
  },
}
